<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" ignored="1" total="12" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="97" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="97" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
      <class name="com.kpit.junit.examples.TestEmployeeBusinessLogic">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="9" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testCalculateAppraisal()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testCalculateAppraisal" duration-ms="10" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCalculateAppraisal -->
        <test-method status="FAIL" signature="testDependant()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testDependant" duration-ms="3" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Dependant failed] but found [Dependant successful]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Dependant failed] but found [Dependant successful]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.kpit.junit.examples.TestEmployeeBusinessLogic.testDependant(TestEmployeeBusinessLogic.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDependant -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="0" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="0" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testException()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testException" duration-ms="3" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at com.kpit.junit.examples.EmployeeBusinessLogic.callMethod(EmployeeBusinessLogic.java:26)
at com.kpit.junit.examples.TestEmployeeBusinessLogic.testException(TestEmployeeBusinessLogic.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testException -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="0" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testYearlySalary()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testYearlySalary" duration-ms="3" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testYearlySalary -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="0" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testParameter(java.lang.String)[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testParameter" duration-ms="2" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sachin]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testParameter -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="0" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testPrimeNumber(java.lang.Integer, boolean)[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testPrimeNumber" duration-ms="2" started-at="2018-06-04T17:19:30Z" data-provider="test1" finished-at="2018-06-04T17:19:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.kpit.junit.examples.TestEmployeeBusinessLogic.testPrimeNumber(TestEmployeeBusinessLogic.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumber -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="2" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testPrimeNumber(java.lang.Integer, boolean)[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testPrimeNumber" duration-ms="1" started-at="2018-06-04T17:19:30Z" data-provider="test1" finished-at="2018-06-04T17:19:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumber -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="0" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testPrimeNumber(java.lang.Integer, boolean)[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testPrimeNumber" duration-ms="1" started-at="2018-06-04T17:19:30Z" data-provider="test1" finished-at="2018-06-04T17:19:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[11]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumber -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="1" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testPrimeNumber(java.lang.Integer, boolean)[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testPrimeNumber" duration-ms="1" started-at="2018-06-04T17:19:30Z" data-provider="test1" finished-at="2018-06-04T17:19:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.kpit.junit.examples.TestEmployeeBusinessLogic.testPrimeNumber(TestEmployeeBusinessLogic.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumber -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="initialize" is-config="true" duration-ms="0" started-at="2018-06-04T17:19:30Z" finished-at="2018-06-04T17:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testPrimeNumber(java.lang.Integer, boolean)[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testPrimeNumber" duration-ms="1" started-at="2018-06-04T17:19:30Z" data-provider="test1" finished-at="2018-06-04T17:19:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumber -->
        <test-method status="SKIP" signature="testDependency()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66]" name="testDependency" duration-ms="0" started-at="2018-06-04T17:19:30Z" depends-on-methods="com.kpit.junit.examples.TestEmployeeBusinessLogic.testDependant" finished-at="2018-06-04T17:19:30Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestEmployeeBusinessLogic.testDependency()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestEmployeeBusinessLogic.testDependency()[pri:0, instance:com.kpit.junit.examples.TestEmployeeBusinessLogic@2344fc66] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDependency -->
      </class> <!-- com.kpit.junit.examples.TestEmployeeBusinessLogic -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
